Complete: To-Do-List Project
OdongAlican/JS-To-Do-List pull request #1
Opened 2020-08-15 09:55 UTC by imahnama

## In this Project We: 
- Used Factories to generate objects for the project
- Used single responsibility rule of Javascript
- Add properties to the To-Do's eg title, description, date and priority
- Add style to enhance UI
- Use localStorage to save user’s projects and todos between sessions.
- Use webpack
- Add ReadMe file
- Add linter files.

2020-08-16 14:14 UTC, suretrust requested changes
Hi team, 👋 

### Great job thus far! 🙌 Please see my comments. 👇 

- [x] The `todo.js` and `allProjects.js` files need some work. DOM-Manipulation and Logic should be in separate modules ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/modules_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/todo-list))
* [x] There should be a 'default' project, it's missing, let's add it.

**KIndly submit another CRR once these issues have been solved.** _Happy coding!_ 🎉

2020-08-16 14:14 UTC, suretrust commented on src/to-do.js
> +    titleInput.type = 'text';
You should separate your application logic (i.e. creating new todos, setting todos as complete, changing todo priority, etc.) from the DOM-related stuff, so keep all of those things in separate modules.

2020-08-17 17:23 UTC, Torres-ssf requested changes
### Changes required :muscle: 
Hi team :hand: 
Great job on this project. Your UI it's really nice :clap: :clap: 
Nice job implementing the requested changes, but we still need to make other changes before moving on.

- [x] Check my comments bellow.

Feel free to message me on slack if you have any questions :smile: 
Happy Coding :computer: 
**Sergio Torres**

2020-08-17 17:23 UTC, Torres-ssf commented on .eslintrc.json
> +      "import/no-cycle": "off"
- [ ] This file is different from the one provided by Microverse [here](https://github.com/microverseinc/linters-config/blob/master/javascript/.eslintrc.json). We should not make changes in this file

2020-08-17 17:23 UTC, Torres-ssf commented on package.json
> +    "build": "webpack"
- [ ] Great job implementing a script to use Webpack. However, it's best practice to create at least 2 scripts for your application, one for development and another one for production. We need to also to inform in which [mode](https://webpack.js.org/configuration/mode/) Webpack will run in these scripts. We will have something like this:
```javascript
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
  },
```

- [ ] We also need to inform users about these script in the README file. This information can be placed in the Usage section. This way users will know how they can use your application.

**OPTIONAL**

- [ ] You can create an even better script for development stages. You will need to add the `
webpack-dev-server` and create a script like this:
```javascript
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  },
```
Running the `start` script will automatically open the index file in the browser, without the need to open it manually

2020-08-17 17:23 UTC, Torres-ssf commented on package.json
> +    "test": "echo \"Error: no test specified\" && exit 1",
- [ ] You can safely remove the test script since it has no purpose.

2020-08-17 17:23 UTC, Torres-ssf commented on README.md
> +![Add To-Do Form](3.png)
Files `1.png`, `2.png`, and `3.png` are not in the root directory of your project. We need to specify the correct directory or they will not be displayed in the README file. Change this to:
```
(images/1.png)
(images/2.png)
(images/3.png)
```

2020-08-18 09:19 UTC, Oghenebrume50 approved these changes
### APPROVED

Hi thanks for making changes as earlier requested by the reviewers, this looks good to me now, please merge and move on **This is approved** :+1: 

**RAPHAEL NORIODE** :mask: STAY_SAFE

2020-08-18 16:13 UTC, merged